name: front_crudaves
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.4

  flutter_lints: ^2.0.0

flutter_native_splash:
    color: "#FFFFFF"
    image: "assets/images/zécarioca.png"
    android: true
    ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/zécarioca.png
